<?php


namespace App\traits;


trait keyName
{
    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'uuid'; // TODO: Change the autogenerated stub
    }
}
