<?php

namespace App\Models;

use App\traits\keyName;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class News extends Model
{
    use keyName ;
    //
    /**
     * @var string[]
     */
    protected $fillable = [
        'title','body','uuid','photo','category_id','user_id' ,'see_first'
    ];

    /**
     *
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($news){
            $news->uuid = Str::uuid();
        });
    }

    /**
     * @param Builder $builder
     * @return Builder
     */
    public function scopeLatest(Builder $builder)
    {
        return $builder->orderBy('created_at' , 'desc')->with(['user','category']);
    }
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category()
    {
        return $this->belongsTo(Categories::class) ;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class) ;
    }
}
