<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Photo extends Model
{
    //
    protected $fillable = [
        'url','user_id'
    ];

    /**
     * boot method
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($photo){
            $photo->uuid = Str::uuid();
        });
    }

    /**
     * @return string
     */
    public function getRouteKeyName()
    {
        return 'uuid'; // TODO: Change the autogenerated stub
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasOne
     */
    public function user()
    {
        return $this->hasOne(User::class) ;
    }
}
